automation: !include_dir_merge_list automations/
sensor: !include_dir_merge_list sensor/
climate: !include_dir_merge_list climate/
binary_sensor: !include_dir_merge_list binary/
input_datetime: !include etc/input_datetime.yaml
input_boolean: !include etc/input_boolean.yaml
input_number: !include etc/input_number.yaml
fan: 
  - platform: xiaomi_miio_fan
    model: dmaker.fan.p18
    name: Xiaomi Smart Fan
    host: 192.168.1.110
    token: 9512a2e9a4c8fb41913b15abf1639dd3