- platform: template
  sensors:
    weather_forecast_temperature:
      friendly_name: "Outside temperature from weather forecast"
      unit_of_measurement: '°C'
    #   value_template: "{{ state_attr('weather.openweathermap','forecast')[1]['temperature'] }}"
      value_template: "{{ state_attr('weather.home', 'temperature') }}"