- platform: statistics
  unique_id: balcony_door_avg10
  name: 'Balcony door: 10 minute average'
  entity_id: sensor.balcony_door_every_minute_report
  state_characteristic: average_step
  max_age:
    minutes: 10