- platform: statistics
  unique_id: balcony_door_avg_v1
  name: 'Balcony door: 10 minute average v1'
  entity_id: sensor.balcony_door_every_minute_report
  state_characteristic: average_step
  max_age:
    minutes: 10