- platform: statistics
  unique_id: balcony_door_avg_v1
  name: 'Balcony door: 10 minute average v1'
  entity_id: sensor.balcony_door_every_minute_report
  state_characteristic: average_step
  max_age:
    minutes: 10

- platform: average
  name: 'Balcony door: Average for 10 min v1.1'
  unique_id: balcony_door_avg_v1_1
  entities:
    - sensor.balcony_door_every_minute_report
  duration:
    minutes: 10