- platform: average
  name: 'Average Espresso Machine Consumption'
  unique_id: average_espresso_machine_power
  entities:
    - sensor.lumi_lumi_plug_mmeu01_analog_input
  duration:
      minutes: 5

- platform: statistics
  name: "Espresso Machine Power mean over last 1 hour"
  entity_id: sensor.lumi_lumi_plug_mmeu01_analog_input
  state_characteristic: mean
  max_age:
    hours: 1

- platform: statistics
  name: "Espresso Machine Power change over 5 minutes"
  entity_id: sensor.lumi_lumi_plug_mmeu01_analog_input
  state_characteristic: change
  max_age:
    minutes: 5
  sampling_size: 50
  precision: 1

- platform: filter
  name: "Unica Power SMA1"
  entity_id: sensor.lumi_lumi_plug_mmeu01_analog_input
  filters:
    - filter: time_simple_moving_average
      window_size: "00:01"
      precision: 0

- platform: filter
  name: "Unica Power SMA5"
  entity_id: sensor.lumi_lumi_plug_mmeu01_analog_input
  filters:
    - filter: time_simple_moving_average
      window_size: "00:05"
      precision: 0

- platform: filter
  name: "Unica Power SMA10"
  entity_id: sensor.lumi_lumi_plug_mmeu01_analog_input
  filters:
    - filter: time_simple_moving_average
      window_size: "00:10"
      precision: 0
