- platform: average
  name: 'Average Espresso Machine Consumption'
  unique_id: average_espresso_machine_power
  entities:
    - sensor.lumi_lumi_plug_mmeu01_analog_input
  duration:
      minutes: 5

- platform: statistics
    name: "Espresso Machine Power mean over last 24 hours"
    entity_id: sensor.lumi_lumi_plug_mmeu01_analog_input
    state_characteristic: mean
    max_age:
      hours: 1

- platform: statistics
  name: "Espresso Machine Power change over 5 minutes"
  entity_id: sensor.lumi_lumi_plug_mmeu01_analog_input
  state_characteristic: change
  max_age:
    minutes: 5
  sampling_size: 50
  precision: 1
